export const DEMO_DATA = [
  {
    id: 1,
    name: "Ahmed Ayman",
    number: "01050554072",
    avatar: "user-1.jpg",
    ticketName: "C-101",
    price: 40,
    cinemaName:
      "Cinema Misr, Mall of Arabia, Burj Al-Atan, Saraya Al-Qubba, Sednawi Mall, Burj Al-Arab",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 2,
    name: "Ahmed Khalid",
    number: "01050554072",
    avatar: "user-2.jpg",
    ticketName: "C-102",
    price: 40,
    cinemaName: "Cinema Nile Plaza, Cairo",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 3,
    name: "Fatima Ali",
    number: "01050554072",
    avatar: "user-3.jpg",
    ticketName: "C-103",
    price: 80,
    cinemaName: "Mall of Sphinx, Giza",
    peopleNumber: 2,
    purchasesNumber: "One Time",
  },
  {
    id: 4,
    name: "Mohammed Hassan",
    number: "01050554072",
    avatar: "user-4.jpg",
    ticketName: "C-104",
    price: 160,
    cinemaName: "Pyramid Cinemas, Luxor",
    peopleNumber: 4,
    purchasesNumber: "One Time",
  },
  {
    id: 5,
    name: "Rana Ahmed",
    number: "01050554072",
    avatar: "user-5.jpg",
    ticketName: "C-105",
    price: 40,
    cinemaName: "Luxor Square Cinemax, Luxor",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 6,
    name: "Aisha Abdullah",
    number: "01050554072",
    avatar: "user-6.jpg",
    ticketName: "C-106",
    price: 40,
    cinemaName: "Cinema Cleopatra Plaza, Cairo",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 7,
    name: "Omar Ibrahim",
    number: "01050554072",
    avatar: "user-7.jpg",
    ticketName: "C-107",
    price: 40,
    cinemaName: "Pharaoh's Premiere Cinemas, Alexandria",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 8,
    name: "Leila Mahmoud",
    number: "01050554072",
    avatar: "user-8.jpg",
    ticketName: "C-108",
    price: 40,
    cinemaName: "Red Sea Reelplex, Hurghada",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },

  {
    id: 9,
    name: "Nour Hadi",
    number: "01050554072",
    avatar: "user-9.jpg",
    ticketName: "C-109",
    price: 40,
    cinemaName: "Cinema Alexandria Oasis, Alexandria",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 10,
    name: "Aliya Kareem",
    number: "01050554072",
    avatar: "user-10.jpg",
    ticketName: "C-110",
    price: 40,
    cinemaName: "Golden Scarab Cineworld, Aswan",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 11,
    name: "Khaled Rania",
    number: "01050554072",
    avatar: "user-11.jpg",
    ticketName: "C-111",
    price: 40,
    cinemaName: "Aswan Star Cinemas, Aswan",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 12,
    name: "Jamilah Nasir",
    number: "01050554072",
    avatar: "user-12.jpg",
    ticketName: "C-112",
    price: 40,
    cinemaName: "Aswan Star Cinemas, Aswan",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 13,
    name: "Mustafa Samir",
    number: "01050554072",
    avatar: "user-13.jpg",
    ticketName: "C-113",
    price: 40,
    cinemaName: "Nubian Nights Multiplex, Aswan",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 14,
    name: "Layla Farid",
    number: "01050554072",
    avatar: "user-14.jpg",
    ticketName: "C-114",
    price: 40,
    cinemaName: "Delta Dreams Cinemas, Tanta",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 15,
    name: "Zainab Karim",
    number: "01050554072",
    avatar: "user-15.jpg",
    ticketName: "C-115",
    price: 40,
    cinemaName: "Sphinx City Screens, Giza",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 16,
    name: "Ibrahim Tariq",
    number: "01050554072",
    avatar: "user-16.jpg",
    ticketName: "C-116",
    price: 40,
    cinemaName: "Oasis Odeon Cinemas, Al Wahat",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 17,
    name: "Noor Hisham",
    number: "01050554072",
    avatar: "user-17.jpg",
    ticketName: "C-117",
    price: 40,
    cinemaName: "Rosetta Roxy Theatres, Rosetta",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 18,
    name: "Amina Rashid",
    number: "01050554072",
    avatar: "user-18.jpg",
    ticketName: "C-118",
    price: 40,
    cinemaName: "Memphis Motion Pictures, Memphis (Mit Rahina)",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 19,
    name: "Hamza Jawad",
    number: "01050554072",
    avatar: "user-19.jpg",
    ticketName: "C-119",
    price: 40,
    cinemaName: "Siwa Starlight Cinemas, Siwa",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 20,
    name: "Fadi Yasmine",
    number: "01050554072",
    avatar: "user-20.jpg",
    ticketName: "C-120",
    price: 40,
    cinemaName: "Eternal Egypt Cineplex, Cairo",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 21,
    name: "Laila Raed",
    number: "01050554072",
    avatar: "user-21.jpg",
    ticketName: "C-121",
    price: 40,
    cinemaName: "Desert Diamond Cineworld, Al Kharga Oasis",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 22,
    name: "Khalil Wafa",
    number: "01050554072",
    avatar: "user-22.jpg",
    ticketName: "C-122",
    price: 40,
    cinemaName: "King Tut's Picture Palace, Luxor",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 23,
    name: "Sara Adel",
    number: "01050554072",
    avatar: "user-23.jpg",
    ticketName: "C-123",
    price: 40,
    cinemaName: "Cairo Horizon Cinemas, Cairo",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 24,
    name: "Tarek Nour",
    number: "01050554072",
    avatar: "user-24.jpg",
    ticketName: "C-124",
    price: 40,
    cinemaName: "Nile Delta Drive-In, Mansoura",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 25,
    name: "Maha Khalifa",
    number: "01050554072",
    avatar: "user-25.jpg",
    ticketName: "C-125",
    price: 40,
    cinemaName: "Abu Simbel Showcase, Abu Simbel",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 26,
    name: "Rami Jamal",
    number: "01050554072",
    avatar: "user-26.jpg",
    ticketName: "C-126",
    price: 40,
    cinemaName: "Amarna AMC Theatres, Akhmim",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 27,
    name: "Amirah Saif",
    number: "01050554072",
    avatar: "user-27.jpg",
    ticketName: "C-127",
    price: 40,
    cinemaName: "Cinema Ramses Royale, Cairo",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
  {
    id: 28,
    name: "Lina Saleh",
    number: "01050554072",
    avatar: "user-28.jpg",
    ticketName: "C-128",
    price: 40,
    cinemaName: "Cleopatra's Choice Cinemas, Alexandria",
    peopleNumber: 1,
    purchasesNumber: "One Time",
  },
];
